# -*- coding: utf-8 -*-
# コンテンツ.xlsx を新構成で作り直し（古いデータをリセット）
# タブ: 短文 / 長文。各3カテゴリー × サブテーマ × タイトル。問題形式なし・精聴/精読。対象レベルはExcelのみ。
import openpyxl
from openpyxl.styles import Font, Alignment, PatternFill
import re
OUT=r"C:/Users/jwpsa/Documents/desktop/claude/safa-japanese-app/コンテンツ.xlsx"

# (カテゴリー, サブテーマ, タイトル, 形式, レベル, 本文, 英訳, キー表現, ポイント, 楽しさ・継続フック, 備考)
TAN = [  # ===== 短文 =====
 # --- ① 生活力（10本・前の倍の長さ・多分野）---
 ("生活力","買い物・お金","スーパーで会計する","対話","N4",
  "店員：いらっしゃいませ。ポイントカードは お持（も）ちですか。\n客：いいえ、持っていません。\n店員：では、お作（つく）りしましょうか。無料（むりょう）です。\n客：あ、けっこうです。急（いそ）いでいるので。\n店員：かしこまりました。お会計（かいけい）は 1,250円（えん）です。袋（ふくろ）は ご利用（りよう）ですか。\n客：はい、一枚（いちまい）ください。\n店員：5円に なります。合計（ごうけい）1,255円です。\n客：カードで お願（ねが）いします。",
  "Clerk: Welcome. Do you have a point card? / Customer: No, I don't. / Clerk: Shall I make one? It's free. / Customer: No thanks, I'm in a hurry. / Clerk: Certainly. That's 1,250 yen. Would you like a bag? / Customer: Yes, one please. / Clerk: That's 5 yen, 1,255 yen total. / Customer: By card, please.",
  "ポイントカードは お持ちですか／けっこうです(=丁寧な断り)／袋は ご利用ですか／カードで","スーパーのレジ一連(ポイント/袋/支払い)を切り抜ける。","「けっこうです」で角を立てずに断れた。","多声TTS:店員/客"),
 ("生活力","買い物・お金","銀行で口座を作る","対話","N3",
  "行員（こういん）：いらっしゃいませ。本日（ほんじつ）は どのような ご用件（ようけん）ですか。\nカイ：口座（こうざ）を 作（つく）りたいんですが。\n行員：ありがとうございます。在留（ざいりゅう）カードと、印鑑（いんかん）か サインは ご用意（ようい）できますか。\nカイ：印鑑は ありませんが、サインでも いいですか。\n行員：はい、大丈夫（だいじょうぶ）です。では、こちらの 用紙（ようし）に お名前（なまえ）と ご住所（じゅうしょ）を ご記入（きにゅう）ください。\nカイ：書（か）けました。\n行員：ありがとうございます。10分（ぷん）ほどで お作（つく）りします。",
  "Teller: Welcome. How may I help you today? / Kai: I'd like to open an account. / Teller: Thank you. Do you have your residence card and a seal (hanko) or signature? / Kai: I don't have a seal—is a signature okay? / Teller: Yes, that's fine. Please fill in your name and address on this form. / Kai: Done. / Teller: Thank you. It'll be ready in about 10 minutes.",
  "口座を 作りたいんですが／印鑑か サイン／ご記入ください","銀行口座の開設を最後まで進める。","印鑑なしでもサインでOKと分かって安心。","多声TTS:行員/客"),
 ("生活力","手続き","市役所で転入届を出す","対話","N3",
  "職員（しょくいん）：こんにちは。ご用件（ようけん）は 何（なん）でしょうか。\nカイ：先月（せんげつ）引（ひ）っ越（こ）してきたので、転入（てんにゅう）の 手続（てつづ）きを したいです。\n職員：かしこまりました。前（まえ）に 住（す）んでいた 市（し）で「転出届（てんしゅつとどけ）」は もらいましたか。\nカイ：はい、これです。\n職員：ありがとうございます。在留（ざいりゅう）カードも お預（あず）かりします。…はい、住所（じゅうしょ）を 変更（へんこう）しました。国民健康保険（こくみんけんこうほけん）も 一緒（いっしょ）に できますが、いかがですか。\nカイ：はい、お願（ねが）いします。",
  "Clerk: Hello, how can I help? / Kai: I moved last month, so I'd like to do the moving-in procedure. / Clerk: Certainly. Did you get a 'moving-out certificate' from your previous city? / Kai: Yes, here it is. / Clerk: Thank you. I'll take your residence card too. ...Done, your address is updated. We can also do national health insurance now—would you like that? / Kai: Yes, please.",
  "転入の 手続き／転出届／一緒に できます","転入届＋保険をまとめて手続き。","ついでに保険も済んで効率的。","多声TTS:職員/来庁者"),
 ("生活力","手続き","病院で受付から診察まで","対話","N4",
  "受付（うけつけ）：こんにちは。今日（きょう）は どうされましたか。\nカイ：きのうから お腹（なか）が 痛（いた）くて…。初（はじ）めてです。\n受付：では、保険証（ほけんしょう）と、この 問診票（もんしんひょう）を お願（ねが）いします。…はい、あちらで お待ちください。\n医者：カイさんですね。どこが 痛みますか。\nカイ：おへその 下（した）あたりが、ずっと 痛いです。\n医者：いつから ですか。熱（ねつ）は ありますか。\nカイ：ゆうべから です。熱は ありません。\n医者：わかりました。少（すこ）し お腹を 見せてください。",
  "Reception: Hello, what's the matter today? / Kai: My stomach has hurt since yesterday... It's my first visit. / Reception: Then your insurance card and this form, please. ...Please wait over there. / Doctor: Kai, right? Where does it hurt? / Kai: Below my navel, it hurts constantly. / Doctor: Since when? Any fever? / Kai: Since last night. No fever. / Doctor: I see. Let me see your stomach.",
  "どうされましたか／問診票／どこが 痛みますか／いつから","受付→問診→診察の流れを通す。","痛いところを伝えられて一安心。","多声TTS:受付/医者/患者"),
 ("生活力","手続き","不動産屋で部屋を借りる","対話","N3",
  "店員：いらっしゃいませ。お部屋（へや）を お探（さが）しですか。\nカイ：はい。駅（えき）から 近くて、家賃（やちん）は 6万円（まんえん）まで が いいです。\n店員：ペットは 飼（か）われますか。\nカイ：いいえ、飼いません。\n店員：では、こちらは いかがですか。駅から 歩（ある）いて 5分（ふん）、家賃 5万8千円（まんはっせん）です。\nカイ：いいですね。中（なか）を 見（み）られますか。\n店員：はい。今（いま）から ご案内（あんない）できます。",
  "Agent: Welcome. Looking for a room? / Kai: Yes. Near the station, rent up to 60,000 yen. / Agent: Will you keep pets? / Kai: No. / Agent: Then how about this? 5 min walk from the station, 58,000 yen. / Kai: Nice. Can I see inside? / Agent: Yes, I can show you now.",
  "お探しですか／家賃は 〜まで／中を 見られますか","部屋探しの条件提示〜内見まで。","条件ぴったりの部屋に出会えた。","多声TTS:店員/客"),
 ("生活力","しごと・学校","アルバイトの面接を受ける","対話","N3",
  "店長：では、面接（めんせつ）を 始（はじ）めます。週（しゅう）に 何日（なんにち）くらい 働（はたら）けますか。\nカイ：平日（へいじつ）の 夕方（ゆうがた）と 週末（しゅうまつ）です。週に 4日（よっか）くらい できます。\n店長：日本語（にほんご）は 大丈夫（だいじょうぶ）ですか。\nカイ：はい、お客（きゃく）さんとの 簡単（かんたん）な 会話（かいわ）は できます。\n店長：いつから 働けますか。\nカイ：来週（らいしゅう）から 大丈夫です。\n店長：わかりました。では、また 連絡（れんらく）します。",
  "Manager: Let's begin the interview. How many days a week can you work? / Kai: Weekday evenings and weekends. About 4 days a week. / Manager: Is your Japanese okay? / Kai: Yes, I can have simple conversations with customers. / Manager: When can you start? / Kai: From next week. / Manager: Got it. We'll contact you.",
  "週に 何日／いつから 働けますか／また 連絡します","バイト面接の定番質問に答える。","緊張の面接、落ち着いて答えられた。","多声TTS:店長/応募者"),
 ("生活力","しごと・学校","上司に報告・相談する","対話","N3",
  "カイ：課長（かちょう）、今（いま）、少（すこ）し よろしいでしょうか。\n課長：はい、どうぞ。\nカイ：実（じつ）は、お客（きゃく）さまから クレームの お電話（でんわ）が ありまして…。\n課長：そうですか。どんな 内容（ないよう）でしたか。\nカイ：商品（しょうひん）が 届（とど）かない、と。すぐに 確認（かくにん）して、明日（あした）までに ご連絡（れんらく）すると お伝（つた）えしました。\n課長：いい 対応（たいおう）です。私（わたし）からも 確認しておきます。",
  "Kai: Section chief, do you have a moment? / Chief: Yes, go ahead. / Kai: Actually, a customer called with a complaint... / Chief: I see. What was it about? / Kai: That the product hasn't arrived. I said I'd check and contact them by tomorrow. / Chief: Good handling. I'll check on my side too.",
  "少し よろしいでしょうか／実は／〜と お伝えしました","トラブルを上司に報連相する。","きちんと対応＝褒められた達成。","多声TTS:部下/上司"),
 ("生活力","移動","駅で乗り換えと遅延を聞く","対話","N3",
  "カイ：すみません、横浜（よこはま）へ 行きたいんですが、どう 行けば いいですか。\n駅員：横浜ですね。3番線（ばんせん）の 電車に 乗（の）って、品川（しながわ）で 乗り換（か）えてください。\nカイ：ありがとうございます。あ、電車は 遅（おく）れていますか。\n駅員：はい、事故（じこ）の 影響（えいきょう）で、10分（ぷん）ほど 遅れています。\nカイ：急（いそ）いでいるので、ほかの 行き方（かた）は ありますか。\n駅員：バスも ありますが、電車の ほうが 早（はや）いと 思います。",
  "Kai: Excuse me, I want to go to Yokohama—how do I get there? / Staff: Yokohama? Take the train on track 3 and change at Shinagawa. / Kai: Thanks. Are the trains delayed? / Staff: Yes, about 10 minutes due to an accident. / Kai: I'm in a hurry—is there another way? / Staff: There's a bus, but the train is faster.",
  "どう 行けば いいですか／〜で 乗り換えて／ほかの 行き方は","経路案内＋遅延時の代替を聞く。","焦りつつ最善ルートを確保。","多声TTS:客/駅員"),
 ("生活力","移動","道に迷って交番で聞く","対話","N4",
  "カイ：すみません、道（みち）に 迷（まよ）って しまって…。この 住所（じゅうしょ）に 行きたいんです。\n警官（けいかん）：どれどれ。ああ、ここですね。この 道を まっすぐ 行って、二（ふた）つ目（め）の 信号（しんごう）を 左（ひだり）です。\nカイ：二つ目の 信号を 左ですね。\n警官：はい。そこから 歩（ある）いて 3分（ぷん）くらいです。\nカイ：ありがとうございます。助（たす）かりました。",
  "Kai: Excuse me, I'm lost... I want to go to this address. / Officer: Let me see. Ah, here. Go straight on this road and turn left at the second light. / Kai: Left at the second light. / Officer: Yes. About a 3-minute walk from there. / Kai: Thank you, that helps.",
  "道に 迷って／まっすぐ 行って／〜を 左","交番で道を尋ねてたどり着く。","親切な警官に助けられ一安心。","多声TTS:客/警官"),
 ("生活力","買い物・お金","スマホを契約する","対話","N3",
  "店員：ご契約（けいやく）ですね。在留（ざいりゅう）カードと、お支払（しはら）い方法（ほうほう）は 何（なに）に なさいますか。\nカイ：クレジットカードで お願（ねが）いします。一番（いちばん）安（やす）い プランが いいです。\n店員：では、こちらが 月（つき）2,980円（えん）で、データは 20ギガ 使（つか）えます。\nカイ：電話（でんわ）も できますか。\n店員：はい、5分（ふん）までの 通話（つうわ）は 無料（むりょう）です。\nカイ：いいですね。それに します。",
  "Clerk: Signing up, right? Your residence card, and how will you pay? / Kai: By credit card, please. I'd like the cheapest plan. / Clerk: Then this one is 2,980 yen a month with 20 GB of data. / Kai: Can I make calls too? / Clerk: Yes, calls up to 5 minutes are free. / Kai: Nice. I'll take it.",
  "お支払い方法は／一番 安い プラン／〜できますか","スマホ契約のプランを選ぶ。","安くて十分なプランを選べた満足。","多声TTS:店員/客"),
 # --- ② 使えるひとこと（3本）---
 ("使える一言","依頼・許可・断り","ていねいにお願いする","対話","N4",
  "A：すみません、ちょっと お願（ねが）いが あるんですが。\nB：はい、何（なん）でしょう。\nA：この 書類（しょるい）、コピーして いただけますか。\nB：いいですよ。何枚（なんまい）ですか。\nA：3枚（まい）、お願いします。\nB：はい、わかりました。",
  "A: Excuse me, I have a small favor. / B: Sure, what is it? / A: Could you copy this document for me? / B: Sure. How many? / A: Three, please. / B: Okay, got it.",
  "お願いが あるんですが／〜ていただけますか／いいですよ","丁寧に頼み、引き受ける。","丁寧表現でスムーズに依頼できた。","多声TTS:A/B"),
 ("使える一言","お礼・謝罪","お礼と謝罪のひとこと","一人称","N4",
  "きのう、先輩（せんぱい）に 仕事（しごと）を 教（おし）えて もらった。とても 助（たす）かったので、「ありがとうございました。とても 勉強（べんきょう）に なりました」と お礼（れい）を 言（い）った。失敗（しっぱい）した ときは、「申（もう）し訳（わけ）ありません」と すぐに 謝（あやま）る。日本（にほん）では お礼と 謝罪（しゃざい）が とても 大切（たいせつ）だ。",
  "Yesterday a senior colleague taught me the work. It really helped, so I said, 'Thank you very much. I learned a lot.' When I make a mistake, I apologize right away with 'I'm very sorry.' In Japan, thanks and apologies are very important.",
  "勉強に なりました／申し訳ありません／すぐに 謝る","お礼と謝罪の定番フレーズ。","一言で印象が良くなる魔法。","1話者・朗読"),
 ("使える一言","気持ち・相づち","あいづちで会話を続ける","対話","N5",
  "A：きのう、はじめて すしを 食（た）べました。\nB：へえ、そうなんですか。\nA：とても おいしかったです！\nB：いいですね！\nA：Bさんも すきですか。\nB：はい、だいすきです。",
  "A: Yesterday I ate sushi for the first time. / B: Oh, really? / A: It was so delicious! / B: Nice! / A: Do you like it too, B? / B: Yes, I love it.",
  "そうなんですか／いいですね／だいすきです","相づちで会話を続ける。","相づちで会話が弾む楽しさ。","多声TTS:A/B"),
 # --- ③ ことば遊び（3本）---
 ("言葉遊び","今日の擬音語","ふわふわ","解説","N4",
  "今日（きょう）の ことばは「ふわふわ」です。やわらかくて 軽（かる）い ようすを 表（あらわ）します。たとえば、焼（や）きたての パンは「ふわふわ」、空（そら）に うかぶ 雲（くも）も「ふわふわ」、猫（ねこ）の 毛（け）も「ふわふわ」です。物（もの）だけでなく、気持（きも）ちにも 使（つか）えます。うれしくて 心（こころ）が 軽い ときは「気持ちが ふわふわする」と 言（い）います。日本語（にほんご）には こんな 音（おと）の 言葉（オノマトペ）が たくさん あって、使うと 表現（ひょうげん）が ぐっと 生（い）き生（い）きします。みなさんも 今日 ひとつ 使ってみませんか。",
  "Today's word is 'fuwafuwa.' It describes something soft and light. For example, freshly baked bread is 'fuwafuwa,' clouds floating in the sky are 'fuwafuwa,' and a cat's fur is 'fuwafuwa.' It works for feelings too, not just objects. When you're happy and your heart feels light, you say 'my heart feels fuwafuwa.' Japanese has many of these sound-words (onomatopoeia), and using them makes your expression much more vivid. Why not try using one today?",
  "ふわふわ(=soft & light)／気持ちが ふわふわする／オノマトペ","擬音語の意味と、物・気持ち両方への使い方。","使うと表現が生き生き＝今日ひとつ使ってみたくなる。","1話者・解説"),
 ("言葉遊び","ことわざ・慣用句","猫の手も借りたい","一人称","N3",
  "「猫（ねこ）の 手（て）も 借（か）りたい」という 言葉（ことば）が あります。とても 忙（いそが）しくて、誰（だれ）の 助（たす）けでも ほしい、という 意味（いみ）です。猫は 手伝（てつだ）って くれませんが、それでも 借りたい くらい 忙しい、ということです。年末（ねんまつ）は みんな 猫の手も 借りたいほど 忙しいです。",
  "There's a saying, 'I'd even borrow a cat's paw.' It means you're so busy you'd want anyone's help. A cat won't actually help, but you're so busy you'd even want to borrow its paw. At year-end, everyone is that busy.",
  "猫の手も 借りたい(=so busy)／〜くらい／〜という 意味","慣用句の意味と由来。","猫が手伝う?の面白い発想。","1話者・解説"),
 ("言葉遊び","カタカナ語","和製英語に気をつけて","一人称","N4",
  "日本語（にほんご）には、英語（えいご）から 来（き）た 言葉（ことば）が たくさん あります。でも、意味（いみ）が 少（すこ）し 違（ちが）う ものも あります。たとえば「マンション」は、英語の 大（おお）きな 家（いえ）では なく、アパートのような 建物（たてもの）の ことです。「サラリーマン」も 和製英語（わせいえいご）で、会社員（かいしゃいん）の ことです。",
  "Japanese has many words from English, but some have slightly different meanings. For example, 'manshon' isn't a big mansion; it's an apartment-like building. 'Sarariiman' is also Japanese-made English, meaning a company employee.",
  "〜から 来た 言葉／意味が 違う／和製英語","和製英語の落とし穴。","「え、違うの!?」の驚き。","1話者・解説"),
 # --- ④ 文化と本音（長文から短文へ移動・短い読み物）---
 ("本音講座","","「大丈夫です」の正体","解説","N3",
  "日本語（にほんご）の「大丈夫（だいじょうぶ）です」は、便利（べんり）ですが、少（すこ）し ふくざつです。「コーヒー、いかがですか」「あ、大丈夫です」。これは「いりません」という 意味（いみ）です。でも、「明日（あした）、来（こ）られますか」「大丈夫です」なら「行（い）けます」という 意味。同（おな）じ 言葉（ことば）でも、場面（ばめん）で 意味が 変（か）わります。困（こま）ったら、相手（あいて）の 顔（かお）を 見（み）て 確認（かくにん）しましょう。",
  "Japanese 'daijoubu desu' is handy but a bit complex. 'Would you like coffee?' 'Oh, daijoubu desu.' Here it means 'No thanks.' But 'Can you come tomorrow?' 'Daijoubu desu' means 'I can go.' The same words change meaning by situation. If unsure, check the other person's face.",
  "大丈夫です(=No thanks / OK)／場面で 意味が 変わる","多義的な「大丈夫」を読み解く。","「え、両方!?」の発見＝SNS映え。","1話者・解説"),
 ("日本と世界の違い","","日本の電車は静か","読み物","N4",
  "日本（にほん）の 電車（でんしゃ）に 乗（の）ると、おどろくことが あります。とても 静（しず）かなのです。みんな スマホを 見（み）たり、寝（ね）たり して、ほとんど 話（はな）しません。電話（でんわ）も マナーモードです。最初（さいしょ）は さびしく 感（かん）じましたが、今（いま）は その 静かさが 心地（ここち）よいです。みなさんの 国（くに）の 電車は どうですか。",
  "When you ride a train in Japan, something may surprise you: it's very quiet. Everyone looks at their phone or sleeps, and hardly anyone talks. Phones are on silent mode. At first I felt it was lonely, but now I find that quietness pleasant. What are trains like in your country?",
  "〜と、〜／ほとんど 話しません／心地よい","文化比較の読み物。","「わかる!」共感で拡散。","1話者・朗読"),
 ("グルメ","","ラーメンを食べよう","読み物","N4",
  "日本（にほん）に 来（き）たら、ぜひ ラーメンを 食（た）べてみてください。ラーメンには いろいろな 種類（しゅるい）が あります。しょうゆ、塩（しお）、みそ、とんこつ…。お店（みせ）に よって 味（あじ）が ちがいます。注文（ちゅうもん）の とき、「麺（めん）の かたさ」を 選（えら）べる 店（みせ）も あります。かたいのが 好（す）きなら「かため」と 言（い）いましょう。あなたの 好（す）きな ラーメンは どれですか。",
  "When you come to Japan, definitely try ramen. There are many kinds: soy sauce, salt, miso, tonkotsu... The taste differs by shop. When ordering, some shops let you choose 'noodle firmness.' If you like it firm, say 'katame.' Which ramen is your favorite?",
  "ぜひ 〜てみてください／〜によって／〜と 言いましょう","紹介＋注文の実用。","おいしそうで食欲がわく。","1話者・朗読"),
 ("文化","","お花見の楽しみ方","読み物","N4",
  "日本（にほん）の 春（はる）の 楽（たの）しみと いえば、お花見（はなみ）です。桜（さくら）が 咲（さ）くと、人々（ひとびと）は 公園（こうえん）に 集（あつ）まり、木（き）の 下（した）で お弁当（べんとう）を 食（た）べたり、おしゃべりを したり します。夜（よる）の 桜「夜桜（よざくら）」も きれいです。桜は 一週間（いっしゅうかん）ほどで 散（ち）って しまうので、その 短（みじか）い 美（うつく）しさを みんなで 楽（たの）しみます。",
  "Speaking of spring fun in Japan, it's hanami (cherry-blossom viewing). When the cherry trees bloom, people gather in parks, eating bento and chatting under the trees. The blossoms at night, 'yozakura,' are beautiful too. The blossoms scatter in about a week, so everyone enjoys that brief beauty together.",
  "〜と いえば／〜たり 〜たり／散ってしまう","お花見の文化。","日本の春の風物詩。","1話者・朗読"),
 ('文化', '', '温泉に入る前に', '解説', 'N4', '日本（にほん）の 温泉（おんせん）には、楽（たの）しむための ルールが あります。まず、湯（ゆ）に 入（はい）る 前（まえ）に、体（からだ）を きれいに 洗（あら）います。そして、タオルは 湯（ゆ）の 中（なか）に 入（い）れません。頭（あたま）の 上（うえ）に のせる 人（ひと）も います。大（おお）きな 声（こえ）で さわがず、ゆっくり 温（あたた）まりましょう。マナーを 守（まも）れば、誰（だれ）でも 気持（きも）ちよく 過（す）ごせます。', "Japanese hot springs have rules for everyone's enjoyment. First, wash your body well before getting in. Don't put your towel in the water; some people rest it on their head. Don't be loud—relax and warm up slowly. If you follow the manners, everyone can have a pleasant time.", '〜てから／〜ません／〜ば', '温泉の基本マナー。', '知らないと恥ずかしい温泉作法。', '1話者・朗読'),
 ('文化', '', 'お正月の過ごし方', '読み物', 'N4', '日本（にほん）の お正月（しょうがつ）は、一年（いちねん）で いちばん 大切（たいせつ）な 行事（ぎょうじ）です。大（おお）みそかの 夜（よる）には「年越（としこ）しそば」を 食（た）べ、元日（がんじつ）には 神社（じんじゃ）へ「初詣（はつもうで）」に 行（い）きます。家族（かぞく）で「おせち料理（りょうり）」を 食（た）べ、子（こ）どもは「お年玉（としだま）」を もらって 喜（よろこ）びます。『あけまして おめでとうございます』と あいさつを して、新（あたら）しい 年（とし）を 祝（いわ）います。', "New Year is the most important event of the year in Japan. On New Year's Eve people eat 'toshikoshi soba,' and on New Year's Day they visit a shrine for 'hatsumode.' Families eat 'osechi' dishes, and children are delighted to receive 'otoshidama' (money gifts). People greet each other with 'Happy New Year' and celebrate the new year.", '〜には／初詣／あけまして おめでとうございます', '正月の主な習慣。', 'お年玉やおせちにわくわく。', '1話者・朗読'),
 ('文化', '', '「いただきます」の心', '解説', 'N3', '日本人（にほんじん）は 食事（しょくじ）の 前（まえ）に『いただきます』、後（あと）に『ごちそうさまでした』と 言（い）います。これは ただの あいさつでは ありません。野菜（やさい）や 肉（にく）など、食（た）べ物（もの）の「命（いのち）」と、料理（りょうり）を 作（つく）ってくれた 人（ひと）への 感謝（かんしゃ）の 言葉（ことば）です。だから、たとえ 一人（ひとり）で 食（た）べる ときでも、小（ちい）さな 声（こえ）で 言（い）う 人（ひと）が 多（おお）いのです。', "Before eating, Japanese people say 'itadakimasu,' and after, 'gochisosama deshita.' These aren't just greetings. They are words of gratitude for the 'life' of the food—vegetables, meat—and for the person who cooked it. That's why many people say them quietly even when eating alone.", 'ただの〜では ない／〜てくれた／たとえ〜ても', '食前後のあいさつの意味。', '知ると食事が少し豊かに。', '1話者・朗読'),
 ('文化', '', '花火大会の夜', '読み物', 'N4', '夏（なつ）の 日本（にほん）と いえば、花火大会（はなびたいかい）です。人々（ひとびと）は「浴衣（ゆかた）」を 着（き）て、屋台（やたい）で やきそばや かき氷（ごおり）を 買（か）います。空（そら）に 大（おお）きな 花火（はなび）が 上（あ）がると、みんな『たまや〜！』と 声（こえ）を あげます。ドンという 音（おと）と、夜空（よぞら）に 広（ひろ）がる 光（ひかり）は、夏（なつ）の いちばんの 思（おも）い出（で）に なります。', "Speaking of summer in Japan, it's fireworks festivals. People wear 'yukata' and buy yakisoba and shaved ice from food stalls. When big fireworks rise into the sky, everyone shouts 'Tamaya!' The booming sound and the light spreading across the night sky become the best memory of summer.", '〜と いえば／〜を 着て／〜が 上がる', '夏祭り・花火の風景。', '浴衣と屋台で気分が上がる。', '1話者・朗読'),
 ('本音講座', '', '「行けたら行く」の意味', '解説', 'N3', '友（とも）だちを 誘（さそ）った とき、『行（い）けたら 行（い）くね』と 言（い）われたら、どう 思（おも）いますか。実（じつ）は これ、多（おお）くの 場合（ばあい）「たぶん 行（い）かない」という 意味（いみ）です。日本人（にほんじん）は、はっきり「行（い）かない」と 言（い）うと 相手（あいて）を がっかりさせる と 考（かんが）えます。だから、やわらかい 断（ことわ）り方（かた）として よく 使（つか）われます。本気（ほんき）の ときは『絶対（ぜったい）行（い）く！』と 言（い）いますよ。', "When you invite a friend and they say 'I'll come if I can,' what do you think? Actually, this often means 'probably not.' Japanese people feel that clearly saying 'I won't come' disappoints the other person, so it's used as a gentle refusal. When they really mean it, they'll say 'I'm definitely coming!'", '〜たら／〜という 意味／断り方', 'やわらかい社交辞令。', '言われてモヤッとする日本語No.1。', '1話者・朗読'),
 ('本音講座', '', '「検討します」の正体', '解説', 'N3', '仕事（しごと）の 場面（ばめん）で『検討（けんとう）します』『前向（まえむ）きに 考（かんが）えます』と 言（い）われたら、注意（ちゅうい）が 必要（ひつよう）です。本当（ほんとう）に 考（かんが）える ことも ありますが、やんわりと「今回（こんかい）は むずかしい」と 伝（つた）えている ことも 多（おお）いのです。日本（にほん）の ビジネスでは、はっきり 断（ことわ）らずに 相手（あいて）の メンツを 守（まも）る 言（い）い方（かた）が 好（この）まれます。', "In business, be careful if you hear 'We'll consider it' or 'We'll think about it positively.' Sometimes they really will, but often it gently means 'this time is difficult.' In Japanese business, ways of speaking that protect the other person's face without refusing outright are preferred.", '検討します／やんわり／〜ことも 多い', 'ビジネスの建前。', 'Yesに聞こえてNoかも。', '1話者・朗読'),
 ('本音講座', '', 'ほめられた時の返事', '対話', 'N3', '田中（たなか）：日本語（にほんご）、お上手（じょうず）ですね！\nカイ：いいえ、まだまだです。\n田中：そんな ことないですよ。発音（はつおん）も きれいだし。\nカイ：ありがとうございます。でも、もっと 勉強（べんきょう）しないと。\n——日本（にほん）では、ほめられた とき すぐに「ありがとう」と 受（う）け取（と）るより、『いいえ、まだまだです』と 謙遜（けんそん）する ことが 多（おお）いです。', "Tanaka: Your Japanese is so good! / Kai: No, I still have a long way to go. / Tanaka: That's not true—your pronunciation is clear too. / Kai: Thank you. But I need to study more. — In Japan, rather than immediately accepting praise with 'thank you,' people often respond modestly with 'No, not yet.'", 'まだまだです／そんな ことない／謙遜', '謙遜の受け答え。', 'ほめ言葉の正しい返し方。', '多声TTS:2名'),
 ('本音講座', '', '「すみません」の七変化', '解説', 'N3', '『すみません』は、日本語（にほんご）で いちばん 便利（べんり）な 言葉（ことば）かもしれません。あやまる とき(=ごめんなさい)、お礼（れい）を 言（い）う とき(=ありがとう)、人（ひと）を 呼（よ）ぶ とき(=ちょっと いいですか)、どれにも 使（つか）えます。たとえば 電車（でんしゃ）で 席（せき）を ゆずって もらったら『すみません』。これは「ありがとう」の 意味（いみ）です。場面（ばめん）で 意味（いみ）が 変（か）わる、ふしぎな 言葉（ことば）です。', "'Sumimasen' may be the most useful word in Japanese. You can use it to apologize (sorry), to thank (thank you), and to get attention (excuse me). For example, if someone gives up their seat for you on the train, you say 'sumimasen'—here it means 'thank you.' It's a curious word whose meaning changes with the situation.", 'すみません／〜たら／場面で 変わる', '万能語すみません。', '1語で3役の最強ワード。', '1話者・朗読'),
 ('日本と世界の違い', '', 'チップがない国', '解説', 'N4', '海外（かいがい）の レストランでは、料理（りょうり）の 代金（だいきん）の ほかに「チップ」を 払（はら）う 国（くに）が 多（おお）いです。でも、日本（にほん）には チップの 習慣（しゅうかん）が ありません。サービス料（りょう）は、最初（さいしょ）から 値段（ねだん）に 入（はい）っています。お店（みせ）の 人（ひと）は、チップを もらわなくても、とても ていねいに サービスして くれます。むしろ チップを 渡（わた）すと、相手（あいて）が 困（こま）って しまう ことも あります。', "In restaurants abroad, many countries pay a 'tip' on top of the bill. But Japan has no tipping custom. The service charge is included in the price from the start. Staff serve very politely even without a tip. In fact, offering a tip can sometimes confuse them.", '〜の ほかに／〜が ない／むしろ', 'チップ文化なし。', '渡すと逆に困らせる!?', '1話者・朗読'),
 ('日本と世界の違い', '', '玄関で靴を脱ぐ', '解説', 'N4', '日本（にほん）の 家（いえ）に 入（はい）る とき、必（かなら）ず 玄関（げんかん）で 靴（くつ）を 脱（ぬ）ぎます。これは、外（そと）の よごれを 家（いえ）の 中（なか）に 入（い）れない ためです。脱（ぬ）いだ 靴（くつ）は、つま先（さき）を 外（そと）の ほうへ 向（む）けて そろえると、きれいに 見（み）えます。学校（がっこう）や 病院（びょういん）、和室（わしつ）の お店（みせ）でも 靴（くつ）を 脱（ぬ）ぐ ことが あります。スリッパに はきかえる ことも 多（おお）いです。', 'When entering a home in Japan, you always take off your shoes at the entrance. This is to keep outside dirt out of the house. If you line up your shoes with the toes pointing outward, it looks neat. Schools, hospitals, and tatami-room restaurants may also require removing shoes, and often you change into slippers.', '〜とき／〜ために／〜と …に 見える', '靴を脱ぐ文化。', '靴の向きまで気を配る。', '1話者・朗読'),
 ('日本と世界の違い', '', 'まだ多い現金文化', '解説', 'N3', '世界（せかい）では カードや スマホ決済（けっさい）が 進（すす）んでいますが、日本（にほん）は 今（いま）でも「現金（げんきん）」を よく 使（つか）います。小（ちい）さな お店（みせ）や 古（ふる）い 食堂（しょくどう）では、カードが 使（つか）えない ことも あります。だから、少（すこ）し 現金（げんきん）を 持（も）って 歩（ある）くと 安心（あんしん）です。最近（さいきん）は キャッシュレスも 増（ふ）えて きましたが、地域（ちいき）に よって 差（さ）が あります。', "While the world moves toward cards and smartphone payments, Japan still uses cash a lot. Small shops and old eateries sometimes don't accept cards. So it's reassuring to carry a little cash. Cashless payment has been increasing recently, but it varies by region.", '〜でも／〜ことも ある／〜によって', '現金がまだ強い。', 'カード不可の店に注意。', '1話者・朗読'),
 ('日本と世界の違い', '', 'きれいに並ぶ国', '解説', 'N4', '駅（えき）や バス停（てい）、お店（みせ）の レジで、日本人（にほんじん）は 自然（しぜん）に 一列（いちれつ）に 並（なら）びます。電車（でんしゃ）を 待（ま）つ ときも、床（ゆか）の 印（しるし）に 沿（そ）って きれいに 並（なら）びます。割（わ）り込（こ）む 人（ひと）は ほとんど いません。みんなが 順番（じゅんばん）を 守（まも）るので、混（こ）んでいても 意外（いがい）と スムーズです。この「並（なら）ぶ 文化（ぶんか）」に 驚（おどろ）く 外国人（がいこくじん）も 多（おお）いです。', "At stations, bus stops, and store registers, Japanese people naturally line up in a single file. Even when waiting for a train, they line up neatly along the marks on the floor. Almost no one cuts in. Because everyone keeps their turn, it's surprisingly smooth even when crowded. Many foreigners are amazed by this 'queuing culture.'", '自然に／〜に 沿って／意外と', '整然と並ぶ。', '列の美しさに驚く。', '1話者・朗読'),
 ('使える一言', '依頼・許可・断り', 'やんわり断る', '対話', 'N3', '同僚（どうりょう）：今日（きょう）、飲（の）みに 行（い）きませんか。\nカイ：ありがとうございます。でも、今日（きょう）は ちょっと…。\n同僚：あ、用事（ようじ）ですか。\nカイ：ええ、また 今度（こんど） ぜひ お願（ねが）いします。\n——『ちょっと…』と 言葉（ことば）を にごすと、はっきり 言（い）わなくても「行（い）けない」と 伝（つた）わります。『また 今度（こんど）』で 次（つぎ）への 気持（きも）ちも 残（のこ）せます。', "Colleague: Want to go for a drink today? / Kai: Thank you. But today is a little... / Colleague: Oh, you have plans? / Kai: Yes—let's definitely do it another time. — By trailing off with 'chotto...,' you convey 'I can't' without saying it directly. 'Another time' leaves the door open for next time.", 'ちょっと…／また 今度／ぜひ', '角を立てない断り。', '魔法の言葉『ちょっと』。', '多声TTS:2名'),
 ('使える一言', '気持ち・相づち', '共感・はげます', '対話', 'N4', '友（とも）だち：最近（さいきん）、仕事（しごと）が 忙（いそが）しくて…。\nカイ：そっか、大変（たいへん）だね。\n友（とも）だち：うん、毎日（まいにち） 残業（ざんぎょう）なんだ。\nカイ：無理（むり）しないでね。体（からだ）に 気（き）を つけて。\n——『大変（たいへん）だね』『無理（むり）しないで』は、相手（あいて）の 気持（きも）ちに 寄（よ）り添（そ）う ひとことです。アドバイスより、まず 共感（きょうかん）が 大切（たいせつ）な ことも あります。', "Friend: Work has been so busy lately... / Kai: I see, that's tough. / Friend: Yeah, overtime every day. / Kai: Don't push yourself. Take care of yourself. — 'That's tough' and 'don't push yourself' are phrases that show empathy. Sometimes empathy matters more than advice.", '大変だね／無理しないで／気を つけて', '共感のひとこと。', '励ましの定番フレーズ。', '多声TTS:2名'),
 ('グルメ', '', 'お寿司の食べ方', '解説', 'N4', 'お寿司（すし）は、はしでも 手（て）でも 食（た）べて いいです。しょうゆは、ネタ(=魚（さかな）)の ほうに 少（すこ）し つけます。ごはんに つけると、ごはんが くずれて しまうからです。わさびが 苦手（にがて）な 人（ひと）は、『さび抜（ぬ）きで』と たのめます。回転（かいてん）寿司（ずし）では、好（す）きな お皿（さら）を 取（と）り、最後（さいご）に お皿（さら）の 数（かず）で 計算（けいさん）します。', "You may eat sushi with chopsticks or your hands. Dip a little soy sauce on the topping (the fish) side; if you dip the rice, it falls apart. If you don't like wasabi, you can ask for 'sabi-nuki' (without wasabi). At conveyor-belt sushi, you take the plates you like and pay at the end by the number of plates.", '〜ても いい／〜から／さび抜きで', '寿司の作法。', 'しょうゆの付け方に通な差。', '1話者・朗読'),
 ('グルメ', '', '居酒屋で注文する', '対話', 'N4', '店員（てんいん）：ご注文（ちゅうもん）は お決（き）まりですか。\nカイ：とりあえず、生（なま）ビールを 二（ふた）つ ください。\n店員：はい、生（なま） 二（ふた）つ。お料理（りょうり）は？\nカイ：からあげと、枝豆（えだまめ）を お願（ねが）いします。\n店員：かしこまりました。\n——居酒屋（いざかや）では『とりあえず 生（なま）！』が 定番（ていばん）。飲（の）み物（もの）を 先（さき）に たのんで、料理（りょうり）は あとから 少（すこ）しずつ 注文（ちゅうもん）します。', "Staff: Are you ready to order? / Kai: For now, two draft beers, please. / Staff: Sure, two drafts. And food? / Kai: Fried chicken and edamame, please. / Staff: Certainly. — At izakaya, 'a draft for now!' is the classic move. You order drinks first and add dishes little by little.", 'とりあえず／〜を ください／お決まりですか', '居酒屋の注文。', '合言葉『とりあえず生』。', '多声TTS:2名'),
 ('グルメ', '', 'ラーメンの種類', '読み物', 'N4', '日本（にほん）の ラーメンには、たくさんの 種類（しゅるい）が あります。スープで 分（わ）けると、しょうゆ、塩（しお）、みそ、とんこつ などが 有名（ゆうめい）です。地域（ちいき）に よって 味（あじ）も ちがい、北海道（ほっかいどう）の みそラーメン、九州（きゅうしゅう）の とんこつラーメンは とくに 人気（にんき）です。麺（めん）の かたさや 味（あじ）の こさを 選（えら）べる お店（みせ）も 多（おお）く、自分（じぶん）好（ごの）みの 一杯（いっぱい）を 見（み）つけられます。', "Japanese ramen comes in many kinds. By soup, soy sauce, salt, miso, and tonkotsu (pork bone) are famous. Flavors differ by region—Hokkaido's miso ramen and Kyushu's tonkotsu ramen are especially popular. Many shops let you choose noodle firmness and flavor strength, so you can find your own perfect bowl.", '〜で 分けると／〜によって／〜好み', 'ラーメンの多様さ。', '自分好みの一杯探し。', '1話者・朗読'),
 ('グルメ', '', 'だしと「うま味」', '解説', 'N3', '和食（わしょく）の おいしさの 秘密（ひみつ）は「だし」に あります。こんぶや かつおぶしから とる だしには、「うま味（み）」と いう 味（あじ）が あります。これは、あまい・からい・すっぱい・にがい・しょっぱい に つづく「第五（だいご）の 味（あじ）」と 言（い）われ、今（いま）では 世界（せかい）でも『UMAMI』として 知（し）られています。だしが きいた みそ汁（しる）は、シンプルでも 深（ふか）い 味（あじ）が します。', "The secret of washoku's deliciousness is 'dashi' (stock). Dashi made from kombu and bonito flakes has a taste called 'umami.' It's called the 'fifth taste' after sweet, spicy, sour, bitter, and salty, and is now known worldwide as 'UMAMI.' Miso soup with good dashi tastes deep even though it's simple.", '〜に ある／〜と 言われ／〜が きく', 'うま味とだし。', '世界に広がるUMAMI。', '1話者・朗読'),
 ('言葉遊び', '今日の擬音語', 'ぺこぺこ・ぐうぐう', '解説', 'N4', 'おなかが すいた とき、日本語（にほんご）では『おなかが ぺこぺこ』と 言（い）います。とても すいて いる ようすです。おなかが 鳴（な）る 音（おと）は『ぐう〜』。たくさん 食（た）べて おなかが いっぱいに なると『ぱんぱん』。眠（ねむ）くて たまらない ときは『うとうと』します。気持（きも）ちや 体（からだ）の ようすを、音（おと）で 表（あらわ）す のが 擬音語（ぎおんご）の おもしろさです。', "When you're hungry, in Japanese you say your stomach is 'peko-peko'—the state of being very hungry. The sound of a growling stomach is 'guu~.' When you've eaten a lot and are full, it's 'pan-pan.' When you're terribly sleepy, you 'uto-uto' (doze off). Expressing feelings and bodily states with sounds is the fun of onomatopoeia.", 'ぺこぺこ／ぐう／ぱんぱん／うとうと', '体調の擬音語。', '音で気分まるわかり。', '1話者・朗読'),
 ('言葉遊び', 'ことわざ・慣用句', '猿も木から落ちる', '読み物', 'N3', '『猿（さる）も 木（き）から 落（お）ちる』は、有名（ゆうめい）な ことわざです。木登（きのぼ）りが 上手（じょうず）な 猿（さる）でも、ときには 木（き）から 落（お）ちる。つまり、どんなに 得意（とくい）な 人（ひと）でも、失敗（しっぱい）する ことが ある、という 意味（いみ）です。にた ことわざに『かっぱの 川流（かわなが）れ』『弘法（こうぼう）も 筆（ふで）の あやまり』が あります。失敗（しっぱい）した 友（とも）だちを なぐさめる ときに 使（つか）えます。', "'Even monkeys fall from trees' is a famous proverb. Even monkeys, who are good climbers, sometimes fall. In other words, even the most skilled person can make mistakes. Similar proverbs are 'even a kappa gets swept down the river' and 'even Kobo makes a slip of the brush.' You can use it to comfort a friend who has failed.", '〜も 〜から 落ちる／つまり／〜ことが ある', '失敗は誰にでも。', '落ち込む友へ贈る一言。', '1話者・朗読'),
]

CHO = [  # ===== 長文 =====
 # --- ① ラジオトーク ---
 ("ラジオトーク","ニュース","桜が満開（国内）","ニュース","N3",
  "おはようございます。今朝（けさ）の ニュースです。昨日（きのう）、東京（とうきょう）の 公園（こうえん）で 桜（さくら）が 満開（まんかい）に なりました。週末（しゅうまつ）は たくさんの 家族（かぞく）連（づ）れで にぎわいそうです。天気（てんき）も よく、お花見（はなみ）に ぴったりの 一日（いちにち）に なるでしょう。一方（いっぽう）、来週（らいしゅう）からは 少（すこ）し 寒（さむ）く なるという 予報（よほう）も 出（で）ています。体調（たいちょう）に 気（き）を つけて お過（す）ごしください。では、今日（きょう）も よい 一日を。",
  "Good morning. Here's this morning's news. Yesterday, the cherry blossoms reached full bloom in a Tokyo park. This weekend it should be crowded with families. The weather is good too—a perfect day for hanami. On the other hand, it's forecast to get a bit colder from next week. Please take care of your health. Have a good day.",
  "今朝の ニュース／満開／〜そうです／一方","ニュースの流れと話題転換「一方」。","季節感で“朝の習慣”に。","1話者・アナウンサー調"),
 ("ラジオトーク","ニュース","全国の天気（天気）","天気予報","N4",
  "全国（ぜんこく）の 天気（てんき）です。今日（きょう）は 西日本（にしにほん）で 晴（は）れますが、東日本（ひがしにほん）は 午後（ごご）から 雲（くも）が 多（おお）く なるでしょう。夜（よる）には 雨（あめ）が 降（ふ）る 所（ところ）も あります。傘（かさ）を 持（も）って 出（で）かけると 安心（あんしん）です。気温（きおん）は 各地（かくち）で 20度（ど）前後（ぜんご）、過（す）ごしやすい 一日（いちにち）に なりそうです。",
  "Here's the nationwide weather. Today it's sunny in western Japan, but in eastern Japan clouds will increase from the afternoon. Some areas may see rain at night. It's safer to take an umbrella. Temperatures will be around 20 degrees—a comfortable day.",
  "晴れます／雲が 多く なる／傘を 持って","全国天気の聞き取り（地域差）。","「傘いる?」毎朝役立つ。","1話者・予報士調"),
 ("ラジオトーク","ニュース","海外のニュース（国際）","ニュース","N3",
  "こんにちは、国際（こくさい）ニュースです。アメリカで、新（あたら）しい 技術（ぎじゅつ）の 会議（かいぎ）が 開（ひら）かれました。世界中（せかいじゅう）から たくさんの 研究者（けんきゅうしゃ）が 集（あつ）まりました。日本（にほん）からも 多（おお）くの 企業（きぎょう）が 参加（さんか）し、注目（ちゅうもく）を 集（あつ）めています。来年（らいねん）は アジアでも 同（おな）じ 会議が 開かれる 予定（よてい）です。",
  "Hello, international news. In the U.S., a conference on new technology was held. Many researchers gathered from around the world. Many companies from Japan also took part and are drawing attention. Next year, the same conference is scheduled to be held in Asia too.",
  "国際ニュース／〜が 開かれました／注目を 集めています","国際ニュースの定型表現。","世界とつながる話題。","1話者・アナウンサー調"),
 ("ラジオトーク","ニュース","サッカーの試合（スポーツ）","ニュース","N4",
  "スポーツの ニュースです。昨日（きのう）、サッカーの 試合（しあい）が ありました。日本（にほん）チームは 2対（たい）1で 勝（か）ちました。最後（さいご）の ゴールは、とても すばらしかったです。スタジアムの ファンは 大（おお）きな 声（こえ）で 応援（おうえん）しました。次（つぎ）の 試合は 来週（らいしゅう）の 土曜日（どようび）です。楽（たの）しみですね。",
  "Sports news. Yesterday there was a soccer match. The Japan team won 2 to 1. The final goal was wonderful. Fans in the stadium cheered loudly. The next match is next Saturday. Something to look forward to.",
  "2対1で 勝ちました／応援しました／楽しみですね","スポーツ結果(点数/勝敗)の聞き取り。","勝利の興奮。","1話者・アナウンサー調"),
 ("ラジオトーク","お便り相談室","勉強が続かない","トーク","N3",
  "こんばんは、パーソナリティの ユウキです。今日（きょう）も 一日（いちにち）お疲（つか）れさまでした。さて、リスナーの みなさんから お便（たよ）りを いただきました。「最近（さいきん）、日本語（にほんご）の 勉強（べんきょう）が 続（つづ）かなくて 困（こま）っています」。わかります〜。でも、大丈夫（だいじょうぶ）。毎日（まいにち）5分（ふん）でも いいんです。好（す）きな ドラマや 歌（うた）で 楽（たの）しく 続（つづ）けましょう。それでは、今夜（こんや）の 一曲（いっきょく）です。",
  "Good evening, this is your host, Yuki. Thanks for your hard work today. Now, a message from a listener: 'Lately I can't keep up my Japanese study and I'm troubled.' I understand! But it's okay. Even 5 minutes a day is fine. Keep it up enjoyably with dramas or songs you like. Now, tonight's song.",
  "お疲れさまでした／お便り／〜ましょう","相談＋励ましの語り口。","共感＝続けたくなる。","1話者・パーソナリティ調"),
 ("ラジオトーク","お便り相談室","漢字が覚えられない","トーク","N3",
  "今日（きょう）の お便（たよ）りです。「漢字（かんじ）が なかなか 覚（おぼ）えられません」。わかります。漢字は 数（かず）が 多（おお）いですからね。おすすめは、毎日（まいにち）少（すこ）しずつ、生活（せいかつ）の 中（なか）で 見（み）た 漢字を 覚（おぼ）えることです。看板（かんばん）や メニューも いい 教材（きょうざい）ですよ。あせらず 続（つづ）けましょう。",
  "Today's listener message: 'I just can't memorize kanji.' I understand—there are so many. My tip: learn a little every day, from kanji you see in daily life. Signs and menus make good study material too. Don't rush—keep at it.",
  "なかなか 〜られません／少しずつ／あせらず 続けましょう","相談＋アドバイスの語り。","共感＆励ましで続く。","1話者・パーソナリティ調"),
 ("ラジオトーク","ゲストインタビュー","ゲストのカイさん","対話","N4",
  "司会（しかい）：今日（きょう）の ゲストは、日本（にほん）で 勉強（べんきょう）している カイさんです。日本に 来て どのくらいですか。\nカイ：2年（ねん）です。\n司会：日本で 一番（いちばん）好（す）きな ものは？\nカイ：温泉（おんせん）です。とても 気持（きも）ちが いいです。\n司会：これから 何（なに）を したいですか。\nカイ：日本語（にほんご）を もっと 上手（じょうず）に なりたいです。\n司会：いいですね！ がんばってください。",
  "Host: Today's guest is Kai, who is studying in Japan. How long have you been in Japan? / Kai: Two years. / Host: What's your favorite thing in Japan? / Kai: Hot springs. They feel so good. / Host: What do you want to do from now on? / Kai: I want to get better at Japanese. / Host: Nice! Keep it up.",
  "どのくらいですか／一番 好きな ものは？／がんばってください","インタビューの定番質問。","多様な人の声・人間味。","多声TTS:司会/ゲスト"),
 ("ラジオトーク","2人のフリートーク","週末どうだった？","対話","N4",
  "A：週末（しゅうまつ）、どうだった？\nB：友（とも）だちと 海（うみ）に 行（い）ったよ。すごく きれいだった！\nA：いいなあ。私（わたし）は 一日中（いちにちじゅう）、家（いえ）で ドラマを 見（み）てた。\nB：それも いいよね。何（なに）の ドラマ？\nA：日本（にほん）の 恋愛（れんあい）ドラマ。じつは 日本語の 勉強（べんきょう）にも なるんだ。\nB：へえ、いいね！",
  "A: How was your weekend? / B: I went to the beach with friends. It was so beautiful! / A: Nice. I watched dramas at home all day. / B: That's good too. What drama? / A: A Japanese romance drama. Actually it's good Japanese study too. / B: Oh, nice!",
  "どうだった?／〜に 行ったよ／勉強にも なる","友だち同士の自然な雑談。","ゆるい会話＝多聴に最適。","多声TTS:友人2人"),
 # --- ② 物語（会話形式＋ナレーション。会話表現を意図的に含む）---
 # カイの物語：日本生活スタート
 ("カイの物語","日本生活スタート","空港に着いた","物語","N5",
  "（ナレーション）長（なが）い フライトの あと、カイは ついに 日本（にほん）に 着（つ）いた。空港（くうこう）は 人（ひと）で いっぱいだ。\n審査官（しんさかん）：パスポートを お願（ねが）いします。日本（にほん）には 何（なん）の ために 来（き）ましたか。\nカイ：えっと、留学（りゅうがく）です。日本語（にほんご）の 学校（がっこう）に 通（かよ）うんです。\n審査官：どのくらい いますか。\nカイ：1年（ねん）の 予定（よてい）です。\n審査官：はい、どうぞ。日本での 生活（せいかつ）、がんばってください。\nカイ：ありがとうございます！\n（ナレーション）スタンプを もらって、カイは 大（おお）きく 息（いき）を ついた。「やっと 来た…。これから 新（あたら）しい 毎日（まいにち）が 始（はじ）まるんだ」。",
  "(Narration) After the long flight, Kai finally arrived in Japan. The airport is packed. / Officer: Passport, please. What did you come to Japan for? / Kai: Um, to study. I'll attend a Japanese language school. / Officer: How long will you stay? / Kai: About a year. / Officer: All right, go ahead. Good luck with your life in Japan. / Kai: Thank you! / (Narration) After getting the stamp, Kai let out a big breath. 'I'm finally here... A new daily life starts now.'",
  "えっと／〜んです／がんばってください","入国の会話＋心情。会話表現「えっと/〜んです/〜んだ」。","新生活 第1話・ドキドキ。","多声TTS:ナレーター/審査官/カイ"),
 ("カイの物語","日本生活スタート","ゴミ出しでこまった","物語","N4",
  "（ナレーション）引（ひ）っ越（こ）しの 次（つぎ）の 日（ひ）。カイは ゴミぶくろを 持（も）って、こまっていた。\nカイ：あれ？ ゴミは どこに 出（だ）せば いいんだろう…。\n（ナレーション）ちょうど、となりの 人（ひと）が 通（とお）りかかった。\nカイ：あの、すみません。ゴミの 出（だ）し方（かた）が わからなくて…。\nとなりの人：ああ、燃（も）えるゴミは 月曜（げつよう）と 木曜（もくよう）ですよ。朝（あさ）8時（じ）までに、そこの 角（かど）に 出（だ）してね。\nカイ：そうなんですね！ ありがとうございます。助（たす）かりました。\nとなりの人：困（こま）ったら いつでも 聞（き）いてね。\n（ナレーション）カイは ほっとした。「日本（にほん）の 人（ひと）は 親切（しんせつ）だなあ」。",
  "(Narration) The day after moving. Kai stood there holding a trash bag, troubled. / Kai: Huh? Where am I supposed to put the trash...? / (Narration) Just then, a neighbor passed by. / Kai: Um, excuse me. I don't know how to sort the trash... / Neighbor: Ah, burnable trash is Monday and Thursday. Put it at that corner by 8 a.m. / Kai: Oh, I see! Thank you, that helps. / Neighbor: Ask me anytime you're stuck. / (Narration) Kai felt relieved. 'Japanese people are so kind.'",
  "〜ばいいんだろう／そうなんですね／〜てね","近所での会話＋気づき。会話表現「あれ?/〜なんですね/〜てね」。","短文「生活力」と再会＝らせん。","多声TTS:ナレーター/カイ/近所の人"),
 # カイの物語：日本一人旅
 ("カイの物語","日本一人旅","京都へ行く","物語","N4",
  "（ナレーション）連休（れんきゅう）、カイは はじめて 一人（ひとり）で 京都（きょうと）へ 来た。古（ふる）い お寺（てら）が 美（うつく）しい。\nカイ：わあ、きれい…。あの、すみません、写真（しゃしん）を 撮（と）って もらえますか。\n通行人（つうこうにん）：いいですよ。はい、チーズ！\nカイ：ありがとうございます！\n（ナレーション）お昼（ひる）に、小（ちい）さな お店（みせ）に 入（はい）った。\n店員：いらっしゃい。何（なに）に しますか。\nカイ：抹茶（まっちゃ）の アイス、ください。\n店員：はいよ。京都（きょうと）は どう？\nカイ：最高（さいこう）です！ また 来（き）たいなあ。\n（ナレーション）わすれられない 一日（いちにち）に なった。",
  "(Narration) On the holidays, Kai came to Kyoto alone for the first time. The old temples are beautiful. / Kai: Wow, beautiful... Um, excuse me, could you take a photo? / Passerby: Sure. Okay, cheese! / Kai: Thank you! / (Narration) For lunch, he went into a small shop. / Clerk: Welcome. What'll you have? / Kai: Matcha ice cream, please. / Clerk: Coming up. How's Kyoto? / Kai: It's the best! I want to come again. / (Narration) It became an unforgettable day.",
  "撮って もらえますか／また 来たいなあ／〜はどう?","旅先の会話。会話表現「わあ/はいよ/〜なあ」。","旅情・写真・食。","多声TTS:ナレーター/カイ/通行人/店員"),
 ("カイの物語","日本一人旅","お祭りに行く","物語","N4",
  "（ナレーション）夏（なつ）の 夜（よる）。カイは 友（とも）だちの ミナと お祭（まつ）りに 来た。\nミナ：カイ、ゆかた 似合（にあ）ってる！\nカイ：本当（ほんとう）？ えへへ、はじめて 着（き）たんだ。\nミナ：屋台（やたい）、行（い）こうよ。たこ焼（や）き 食（た）べたい！\nカイ：いいね。あ、かき氷（ごおり）も！\n（ナレーション）二人（ふたり）が 食（た）べながら 歩（ある）いていると、空（そら）に 大（おお）きな 花火（はなび）が 上（あ）がった。\nカイ：わあ…！ きれいだね。\nミナ：うん。来（き）て よかったね。\n（ナレーション）大（おお）きな 音（おと）と 光（ひかり）。カイの 胸（むね）は どきどきしていた。",
  "(Narration) A summer night. Kai came to a festival with his friend Mina. / Mina: Kai, the yukata looks good on you! / Kai: Really? Hehe, it's my first time wearing one. / Mina: Let's go to the stalls. I want takoyaki! / Kai: Nice. Oh, shaved ice too! / (Narration) As the two walked while eating, big fireworks rose into the sky. / Kai: Wow...! It's beautiful. / Mina: Yeah. I'm glad we came. / (Narration) The loud sound and light. Kai's heart was racing.",
  "似合ってる／〜たんだ／来て よかったね","友だちとの祭り会話。会話表現「えへへ/〜よ/〜だね」。","夏祭りの高揚・友情。","多声TTS:ナレーター/カイ/ミナ"),
 # カイの物語：カイの日常
 ("カイの物語","カイの日常","はじめての美容院","物語","N4",
  "（ナレーション）カイは はじめて 一人（ひとり）で 美容院（びよういん）に 来た。日本語（にほんご）で 髪型（かみがた）を 言（い）うのは ドキドキする。\n美容師（びようし）：今日（きょう）は どうしますか。\nカイ：えっと、少（すこ）し 短（みじか）く して、軽（かる）く したいんです。\n美容師：前髪（まえがみ）は どうしましょう？\nカイ：前髪は そのままで お願（ねが）いします。\n（ナレーション）はさみの 音（おと）が ひびく。終（お）わって 鏡（かがみ）を 見（み）ると…思（おも）ったより ずいぶん 短（みじか）い！\nカイ：（心の声）うわ、短く なりすぎたかな…。\n美容師：うん、似合（にあ）っていますよ。\nカイ：あ、ありがとうございます！\n（ナレーション）少（すこ）し 短すぎたけれど、カイは なんだか うれしかった。",
  "(Narration) Kai came to a hair salon alone for the first time. Saying his hairstyle in Japanese is nerve-racking. / Stylist: What would you like today? / Kai: Um, a bit shorter and lighter, please. / Stylist: What about your bangs? / Kai: Please leave the bangs as they are. / (Narration) The scissors snip away. When it was done and he looked in the mirror... it was much shorter than he expected! / Kai: (inner voice) Whoa, maybe too short... / Stylist: Yeah, it suits you. / Kai: Oh, thank you! / (Narration) A little too short, but Kai felt somehow happy.",
  "〜したいんです／どうしましょう／似合っています","美容院の会話＋心の声。会話表現「えっと/うわ/なんだか」。","カイの小さな挑戦。","多声TTS:ナレーター/カイ/美容師"),
 ("カイの物語","カイの日常","友だちができた","物語","N4",
  "（ナレーション）日本（にほん）に 来（き）た ばかりの ころ、カイは 友（とも）だちが いなくて さびしかった。ある日（ひ）、日本語（にほんご）の 教室（きょうしつ）で…\nクラスメート：あ、その ペン、いいね。どこで 買（か）ったの？\nカイ：えっ、これ？ 駅前（えきまえ）の お店（みせ）です。\nクラスメート：へえ。ねえ、よかったら いっしょに お昼（ひる）、食（た）べない？\nカイ：いいんですか？ うれしいです！\n（ナレーション）その 一言（ひとこと）が、とても うれしかった。\nカイ：（心の声）勇気（ゆうき）を 出（だ）して よかった…！\n（ナレーション）今（いま）では、休（やす）みの 日（ひ）に いっしょに 出（で）かける 仲（なか）だ。",
  "(Narration) Just after coming to Japan, Kai had no friends and felt lonely. One day, in Japanese class... / Classmate: Oh, that pen's nice. Where'd you buy it? / Kai: Huh, this? At the shop in front of the station. / Classmate: Huh. Hey, if you'd like, want to have lunch together? / Kai: Really? I'd love to! / (Narration) That one phrase made him so happy. / Kai: (inner voice) I'm so glad I found the courage...! / (Narration) Now they're close enough to go out together on days off.",
  "どこで 買ったの？／いっしょに 〜ない？／よかったら","友だち作りの会話。会話表現「えっ/へえ/ねえ」。誘いの「〜ない?」。","一歩ふみ出す勇気＝共感。","多声TTS:ナレーター/カイ/クラスメート"),
 # カイの物語：カイの休憩室
 ("カイの物語","カイの休憩室","好きな食べ物の話","物語","N4",
  "カイ：みなさん、こんにちは、カイです。ちょっと 休憩（きゅうけい）の 時間（じかん）。今日（きょう）は ぼくの 好（す）きな 食（た）べ物（もの）の 話（はなし）。\n（ナレーション）実（じつ）は カイ、おにぎりが 大好物（だいこうぶつ）。\nカイ：コンビニの おにぎりも おいしいけど、自分（じぶん）で 作（つく）るのも 楽（たの）しいんだよね。この前（まえ）、友（とも）だちに 作（つく）ってあげたら「うまっ！」って 言（い）われて、うれしくて さ。\n（ナレーション）カイは 照（て）れながら 笑（わら）った。\nカイ：みなさんの 好（す）きな 日本（にほん）の 食べ物は 何（なん）ですか？ また 教（おし）えてね。じゃあ、また！",
  "Kai: Hi everyone, it's Kai. A little break time. Today, a talk about my favorite food. / (Narration) Actually, Kai loves onigiri. / Kai: Convenience-store onigiri are tasty, but making them yourself is fun too, you know. The other day I made some for a friend and they said 'Yum!'—it made me really happy. / (Narration) Kai laughed bashfully. / Kai: What's your favorite Japanese food? Let me know sometime. See you!",
  "〜んだよね／うまっ／〜てね","カイの語りかけ＋ひとり言。くだけた会話表現「〜だよね/うまっ/さ」。","親近感・リスナーへの呼びかけ。","多声TTS:カイ/ナレーター"),
 # 昔話（会話入り）
 ("昔話","","桃太郎","物語","N4",
  "（ナレーション）むかしむかし、ある ところに、おじいさんと おばあさんが いました。ある日（ひ）、川（かわ）から 大（おお）きな 桃（もも）が どんぶらこ、どんぶらこ、と 流（なが）れて きました。\nおばあさん：おや、なんて 大（おお）きな 桃（もも）だろう！ 家（いえ）に 持（も）って 帰（かえ）りましょう。\n（ナレーション）家（いえ）で 桃（もも）を 切（き）ろうとすると…パカッ！ 中（なか）から 元気（げんき）な 男（おとこ）の子（こ）が 生（う）まれました。\nおじいさん：おお、元気（げんき）な 子（こ）だ！ 名前（なまえ）は 桃太郎（ももたろう）に しよう。\n（ナレーション）大（おお）きく なった 桃太郎（ももたろう）は、ある日（ひ） 言（い）いました。\n桃太郎：おじいさん、おばあさん。鬼（おに）を 退治（たいじ）しに 行（い）ってきます！",
  "(Narration) Long ago, an old man and an old woman lived in a certain place. One day, a big peach came floating down the river, donburako, donburako. / Old woman: Oh my, what a big peach! Let's take it home. / (Narration) When they tried to cut the peach at home... crack! A healthy boy was born from inside. / Old man: Oh, a lively boy! Let's name him Momotaro. / (Narration) When Momotaro grew up, one day he said: / Momotaro: Grandpa, Grandma. I'm going off to defeat the ogres!",
  "なんて 〜だろう／〜ましょう／〜てきます","昔話の会話＋擬音(どんぶらこ/パカッ)。","有名な昔話を会話で。","多声TTS:ナレーター/おばあさん/おじいさん/桃太郎"),
 # ミステリー（旧「日本語ミステリー」。連載「消えた駅弁の謎」）
 ("ミステリー","","消えた駅弁の謎 第1話：駅で事件発生","物語","N4",
  "（ナレーション）東京駅（とうきょうえき）の 有名（ゆうめい）な 駅弁屋（えきべんや）で 事件（じけん）が 起（お）きた。\n店長（てんちょう）：たいへんだ！ 一番（いちばん）人気（にんき）の「うみの幸（さち）弁当（べんとう）」が、10個（こ）も 消（き）えてる！\n駅員（えきいん）の田中（たなか）：鍵（かぎ）は かかっていたんですよね？\n店長：はい、朝（あさ）まで しっかり…。\n田中：おかしいな。鍵（かぎ）が かかっていたのに、どうやって…？\n（ナレーション）田中（たなか）さんは 考（かんが）えた。これは ただの どろぼうでは ないかもしれない。",
  "(Narration) An incident occurred at a famous ekiben shop in Tokyo Station. / Manager: This is terrible! Ten of our most popular 'Sea Bounty Bento' have vanished! / Tanaka (staff): The door was locked, right? / Manager: Yes, firmly until morning... / Tanaka: Strange. The door was locked, so how...? / (Narration) Tanaka thought. This might not be an ordinary thief.",
  "たいへんだ／〜んですよね／どうやって…?","事件の発端を会話で（密室の謎）。","続きが気になる第1話。","多声TTS:ナレーター/店長/田中"),
 ("ミステリー","","消えた駅弁の謎 第2話：証言を聞く","対話","N4",
  "田中（たなか）：すみません、今朝（けさ）、何（なに）か 見（み）ませんでしたか。\n掃除（そうじ）の人：5時（じ）ごろ、白（しろ）い 服（ふく）の 人（ひと）を 見（み）ましたよ。\n田中：白い 服…。ありがとうございます。\nコーヒー店（てん）の人：そういえば、変（へん）な 音（おと）が しましたね。バサバサっと。\n田中：バサバサ？\n（ナレーション）でも、防犯（ぼうはん）カメラには だれも 映（うつ）っていない。\n田中：（首（くび）を かしげて）うーん、おかしいなあ…。",
  "Tanaka: Excuse me, did you see anything this morning? / Cleaner: Around 5, I saw someone in white clothes. / Tanaka: White clothes... Thank you. / Coffee-shop worker: Come to think of it, there was a strange sound. A flapping sound. / Tanaka: Flapping? / (Narration) But the security camera showed no one. / Tanaka: (tilting his head) Hmm, that's strange...",
  "見ませんでしたか／そういえば／うーん","証言の会話と矛盾。会話表現「そういえば/うーん」。","謎が深まる。","多声TTS:田中/証人たち/ナレーター"),
 ("ミステリー","","消えた駅弁の謎 第3話：容疑者登場","対話","N3",
  "（ナレーション）次（つぎ）の 日（ひ）、田中（たなか）さんは 白（しろ）い 服（ふく）の 男（おとこ）を 見（み）つけた。駅（えき）の 清掃員（せいそういん）だ。\n田中：あの 朝（あさ）、何（なに）を していましたか。\n清掃員：私（わたし）は ただ、ゴミを 集（あつ）めていただけですよ。\n（ナレーション）そのとき、男（おとこ）の カバンから 弁当（べんとう）の 包（つつ）み紙（がみ）が ひらり、と 落（お）ちた。\n田中：（目（め）を 光（ひか）らせて）…これは？\n清掃員：えっ、いや、これは…！",
  "(Narration) The next day, Tanaka found the man in white—a station cleaner. / Tanaka: What were you doing that morning? / Cleaner: I was just collecting trash. / (Narration) Just then, a bento wrapper fluttered out of the man's bag. / Tanaka: (eyes flashing) ...What's this? / Cleaner: Huh, no, this is...!",
  "〜だけですよ／これは？／えっ、いや","容疑者への会話と証拠。会話表現「〜だけですよ/えっ、いや」。","犯人か?の緊張。","多声TTS:ナレーター/田中/清掃員"),
 ("ミステリー","","消えた駅弁の謎 第4話：真犯人は？","物語","N3",
  "清掃員：それは、私（わたし）が 拾（ひろ）った ゴミです。本当（ほんとう）です！\n（ナレーション）田中（たなか）さんは 防犯（ぼうはん）カメラを もう一度（いちど）見（み）た。すると、屋根（やね）の すきまから…\n田中：あっ！ 見（み）て ください。大（おお）きな カラスが、弁当（べんとう）を 運（はこ）んでる！\n店長：えーっ！ 犯人（はんにん）は カラス だったの！？\n（ナレーション）みんな 大笑（おおわら）い。鍵（かぎ）の 謎（なぞ）は、屋根（やね）の 小（ちい）さな 窓（まど）だったのだ。\n田中：はは、事件（じけん）は 無事（ぶじ）解決（かいけつ）、ですね。",
  "Cleaner: That's trash I picked up. It's true! / (Narration) Tanaka watched the security camera again. Then, through a gap in the roof... / Tanaka: Ah! Look! A big crow is carrying the bento! / Manager: Whaaat! The culprit was a crow?! / (Narration) Everyone burst out laughing. The mystery of the lock was a small window in the roof. / Tanaka: Haha, case closed.",
  "見て ください／〜だったの!?／無事 解決","真相を会話で。会話表現「あっ/えーっ/はは」。","犯人はカラス＝意外な落ち。","多声TTS:ナレーター/田中/清掃員/店長"),
 # ドキュメンタリー（実話・会話＋ナレーション・濃い内容）
 ("ドキュメンタリー","","カップラーメンの誕生","ドキュメンタリー","N3",
  "（ナレーション）戦後（せんご）の 日本（にほん）。町（まち）には 食（た）べ物（もの）を 求（もと）める 人々（ひとびと）の 長（なが）い 行列（ぎょうれつ）が あった。それを 見（み）て、一人（ひとり）の 男（おとこ）、安藤（あんどう）さんは 強（つよ）く 思（おも）った。\n安藤：お湯（ゆ）を 入（い）れるだけで すぐ 食（た）べられる めんが あれば、みんなが 助（たす）かるはずだ。\n（ナレーション）その日（ひ）から、小（ちい）さな 小屋（こや）に こもる 毎日（まいにち）が 始（はじ）まった。\n妻（つま）：あなた、また 徹夜（てつや）ですか。体（からだ）を こわしますよ。\n安藤：あと 少（すこ）しなんだ。あきらめるわけには いかない。\n（ナレーション）失敗（しっぱい）は 数（かぞ）えきれない。めんが すぐ 悪（わる）くなって しまう。ある日（ひ）、妻（つま）が 作（つく）る 天（てん）ぷらを 見（み）て——\n安藤：そうか！ 油（あぶら）で あげれば、水分（すいぶん）が とんで、めんが かわく！\n（ナレーション）こうして、世界（せかい）で はじめての インスタントラーメンが 生（う）まれた。今（いま）では 世界中（せかいじゅう）で 一年（いちねん）に 1000億（おく）食（しょく）。小（ちい）さな ひらめきが、本当（ほんとう）に 世界（せかい）を 変（か）えたのだ。",
  "(Narration) Postwar Japan. In the towns were long lines of people seeking food. Seeing that, one man, Mr. Ando, thought strongly: / Ando: If there were noodles you could eat right away just by adding hot water, it would help everyone. / (Narration) From that day, days of shutting himself in a small shed began. / Wife: Dear, an all-nighter again? You'll ruin your health. / Ando: Just a little more. I can't give up. / (Narration) The failures were countless—the noodles spoiled quickly. One day, watching his wife make tempura— / Ando: That's it! If you fry them in oil, the water evaporates and the noodles dry! / (Narration) Thus the world's first instant ramen was born. Today, 100 billion servings a year worldwide. A small spark truly changed the world.",
  "〜はずだ／あきらめるわけには いかない／そうか！","困難→不屈→ひらめき→成功。会話で臨場感。","身近なカップ麺の感動秘話・濃い内容。","多声TTS:ナレーター/安藤/妻"),
 ("ドキュメンタリー","","はやぶさの帰還","ドキュメンタリー","N3",
  "（ナレーション）小（ちい）さな 宇宙船（うちゅうせん）「はやぶさ」は、地球（ちきゅう）から 3億（おく）キロ 離（はな）れた 小惑星（しょうわくせい）を 目指（めざ）した。星（ほし）の 石（いし）を 取（と）って 帰（かえ）る——だれも 成功（せいこう）した ことの ない 挑戦（ちょうせん）だった。\n（ナレーション）しかし、旅（たび）は 苦難（くなん）の 連続（れんぞく）。エンジンは こわれ、ついに 通信（つうしん）も 切（き）れた。\n研究者（けんきゅうしゃ）A：信号（しんごう）が…ありません。はやぶさが、いません。\n研究者B：あきらめるな。きっと どこかで 生（い）きている。呼（よ）び続（つづ）けよう。\n（ナレーション）管制室（かんせいしつ）の 人々（ひとびと）は、来（く）る日（ひ）も 来る日も 信号（しんごう）を 送（おく）り続（つづ）けた。そして 7週間後（しゅうかんご）——\n研究者A：…返事（へんじ）が、来（き）ました！ はやぶさ、生（い）きてます！\n（ナレーション）7年（ねん）、60億（おく）キロの 旅（たび）の すえ、はやぶさは 帰（かえ）ってきた。最後（さいご）は 自分（じぶん）の 体（からだ）を 燃（も）やしながら、石（いし）の カプセルだけを そっと 送（おく）り届（とど）けた。その 光（ひかり）に、世界中（せかいじゅう）が 涙（なみだ）した。",
  "(Narration) The small spacecraft 'Hayabusa' aimed for an asteroid 300 million km from Earth. To collect rocks from a star and return—a challenge no one had ever succeeded at. / (Narration) But the journey was one hardship after another. The engines broke, and finally communication was lost. / Researcher A: There's... no signal. Hayabusa is gone. / Researcher B: Don't give up. It's surely alive somewhere. Let's keep calling. / (Narration) The control room kept sending signals day after day. Then, seven weeks later— / Researcher A: ...A reply came! Hayabusa is alive! / (Narration) After seven years and 6 billion km, Hayabusa came home. At the end, burning up its own body, it gently delivered only the capsule of rocks. The whole world wept at that light.",
  "あきらめるな／返事が 来ました／〜のすえ","苦難→不屈→奇跡の帰還。管制室の会話で手に汗。","実話の大感動・濃い内容。","多声TTS:ナレーター/研究者A/研究者B"),
 ('ミステリー', '', '消えた最終電車', '物語', 'N3', '夜（よる）11時（じ）50分（ぷん）、駅員（えきいん）の 木村（きむら）さんは おかしな ことに 気（き）づいた。\n木村：あれ？ さっきまで ホームに いた 女（おんな）の 人（ひと）、どこへ 行（い）ったんだ…。\n終電（しゅうでん）は まだ 来（き）ていない。改札（かいさつ）も 通（とお）っていない。なのに、ホームには 誰（だれ）も いない。\n木村：かばんだけが、ベンチに 残（のこ）っている…。\n次（つぎ）の 朝（あさ）、かばんの 中（なか）から 一枚（いちまい）の 古（ふる）い 切符（きっぷ）が 見（み）つかった。日付（ひづけ）は——30年（ねん）前（まえ）だった。\n（つづく）', "11:50 p.m. Station attendant Kimura noticed something strange. Kimura: Huh? The woman who was on the platform just now—where did she go...? The last train hasn't come yet. She didn't pass the gate. And yet, no one is on the platform. Kimura: Only a bag is left on the bench... The next morning, an old ticket was found inside the bag. The date was—30 years ago. (To be continued)", '〜に 気づいた／なのに／〜だった', '続きが気になる導入。', '30年前の切符の謎。', '多声TTS:ナレーション/駅員'),
 ('ドキュメンタリー', '', '黒部ダムをつくった男たち', 'ドキュメンタリー', 'N3', '昭和（しょうわ）の 時代（じだい）、富山（とやま）の 山（やま）おくに、巨大（きょだい）な ダムを つくる 計画（けいかく）が あった。黒部（くろべ）ダムである。けわしい 山（やま）、冷（つめ）たい 水（みず）、そして 固（かた）い 岩（いわ）。工事（こうじ）は 想像（そうぞう）を こえる 困難（こんなん）の 連続（れんぞく）だった。とくに トンネルを ほる 作業（さぎょう）では、地下水（ちかすい）が ふき出（だ）し、何度（なんど）も 工事（こうじ）が 止（と）まった。それでも 作業員（さぎょういん）たちは あきらめなかった。7年（ねん）の 月日（つきひ）と、のべ 1000万人（まんにん）の 力（ちから）で、ダムは ついに 完成（かんせい）した。今（いま）も 黒部（くろべ）の 水（みず）は、人々（ひとびと）の 暮（く）らしを ささえている。', "In the Showa era, there was a plan to build a huge dam deep in the mountains of Toyama: the Kurobe Dam. Steep mountains, cold water, and hard rock—construction was a series of difficulties beyond imagination. Especially when digging the tunnel, groundwater gushed out and work stopped many times. Still, the workers never gave up. With seven years and the effort of ten million people in total, the dam was finally completed. Even now, Kurobe's water supports people's lives.", '〜を こえる／何度も／それでも', '困難に挑む実話。', '不可能を可能にした執念。', '1話者・朗読'),
 ('ドキュメンタリー', '', '新幹線――夢の超特急', 'ドキュメンタリー', 'N3', '1964年（ねん）、東京（とうきょう）と 大阪（おおさか）を むすぶ「新幹線（しんかんせん）」が 走（はし）り はじめた。当時（とうじ）、時速（じそく）200キロを こえる 電車（でんしゃ）は、世界（せかい）の どこにも なかった。『そんな スピードは あぶない』と 多（おお）くの 人（ひと）が 反対（はんたい）した。技術者（ぎじゅつしゃ）たちは、空気（くうき）の 力（ちから）や 線路（せんろ）の カーブを 何度（なんど）も 計算（けいさん）し、安全（あんぜん）の ために 知恵（ちえ）を しぼった。開業（かいぎょう）の 日（ひ）、新幹線（しんかんせん）は 一度（いちど）の 事故（じこ）も なく 走（はし）りきった。夢（ゆめ）の 超特急（ちょうとっきゅう）は、日本（にほん）の 誇（ほこ）りに なった。', "In 1964, the Shinkansen connecting Tokyo and Osaka began running. At the time, no train anywhere in the world exceeded 200 km/h. 'Such speed is dangerous,' many people opposed. Engineers calculated air resistance and track curves again and again, racking their brains for safety. On opening day, the Shinkansen ran the whole way without a single accident. The dream super-express became a source of pride for Japan.", '〜を こえる／〜の ために／〜きった', '世界初の高速鉄道。', '反対を覆した技術の結晶。', '1話者・朗読'),
 ('ドキュメンタリー', '', '青い光をもとめて', 'ドキュメンタリー', 'N3', '赤（あか）と 緑（みどり）の 光（ひかり）は できても、「青（あお）い 光（ひかり）」を 出（だ）す LEDだけは、だれにも 作（つく）れなかった。『20世紀（せいき）中（じゅう）には 無理（むり）だ』とも 言（い）われた。日本（にほん）の ある 研究者（けんきゅうしゃ）は、小（ちい）さな 会社（かいしゃ）で、たった 一人（ひとり）、何千回（なんぜんかい）も 実験（じっけん）を くりかえした。失敗（しっぱい）、また 失敗（しっぱい）。それでも 手（て）を 止（と）めなかった。ついに 青（あお）い 光（ひかり）が ともった 瞬間（しゅんかん）、世界（せかい）の 明（あ）かりは 変（か）わった。白（しろ）い LEDが 生（う）まれ、街（まち）も 家（いえ）も 明（あか）るく なった。その 功績（こうせき）は、のちに ノーベル賞（しょう）に かがやいた。', "Red and green light were possible, but a blue-light LED was something no one could make. 'It's impossible within the 20th century,' they said. One Japanese researcher, alone at a small company, repeated experiments thousands of times. Failure, and failure again. Still he never stopped. The moment blue light finally lit up, the world's lighting changed. White LEDs were born, brightening streets and homes. The achievement later shone with a Nobel Prize.", '〜だけは／くりかえした／〜瞬間', '青色LEDの挑戦。', '孤独な執念がノーベル賞に。', '1話者・朗読'),
 ('昔話', '', '浦島太郎', '物語', 'N4', 'むかしむかし、浦島太郎（うらしまたろう）という 若者（わかもの）が いました。ある 日（ひ）、いじめられている 亀（かめ）を 助（たす）けて あげました。お礼（れい）に、亀（かめ）は 太郎（たろう）を 海（うみ）の 中（なか）の「竜宮城（りゅうぐうじょう）」へ つれて 行（い）きました。そこは 美（うつく）しい おとめ「乙姫（おとひめ）」が すむ、ゆめのような 場所（ばしょ）でした。楽（たの）しい 日々（ひび）を すごし、太郎（たろう）が 家（いえ）に 帰（かえ）ると——村（むら）は すっかり 変（か）わって いました。なんと、何百年（なんびゃくねん）もの 時（とき）が すぎて いたのです。', "Long ago, there was a young man named Urashima Taro. One day, he rescued a turtle that was being bullied. In return, the turtle took Taro to the 'Dragon Palace' beneath the sea. It was a dreamlike place where the beautiful maiden 'Otohime' lived. After spending happy days there, Taro returned home—but the village had completely changed. Astonishingly, hundreds of years had passed.", '〜て あげる／〜のような／なんと', '助けた恩と時の流れ。', '玉手箱の結末は…?', '1話者・朗読'),
 ('昔話', '', 'かぐや姫', '物語', 'N4', 'むかし、竹（たけ）を とって 暮（く）らす おじいさんが いました。ある 日（ひ）、光（ひか）る 竹（たけ）の 中（なか）から、小（ちい）さな 女（おんな）の 子（こ）が 生（う）まれました。「かぐや姫（ひめ）」と 名（な）づけられた その 子（こ）は、月（つき）のように 美（うつく）しく 育（そだ）ちました。やがて、たくさんの 男（おとこ）たちが 結婚（けっこん）を もうし込（こ）みましたが、姫（ひめ）は 首（くび）を たてに ふりません。実（じつ）は、かぐや姫（ひめ）は 月（つき）の 世界（せかい）から 来（き）た 人（ひと）でした。満月（まんげつ）の 夜（よる）、姫（ひめ）は 月（つき）へ 帰（かえ）って いきました。', "Long ago, there was an old man who made his living cutting bamboo. One day, a tiny girl was born from a glowing stalk of bamboo. Named 'Kaguya-hime,' she grew as beautiful as the moon. In time, many men proposed marriage, but the princess would not nod yes. In fact, Kaguya-hime was a person from the world of the moon. On the night of the full moon, she returned to the moon.", '〜の中から／〜のように／やがて', '竹から生まれた姫。', '日本最古の物語の一つ。', '1話者・朗読'),
 ('昔話', '', '鶴の恩返し', '物語', 'N3', 'さむい 冬（ふゆ）の 日（ひ）、ある 男（おとこ）が、わなに かかった 鶴（つる）を 助（たす）けました。その 夜（よる）、美（うつく）しい 女（おんな）の 人（ひと）が 家（いえ）を たずねて きて、男（おとこ）の 妻（つま）に なりました。妻（つま）は『けっして 見（み）ないで ください』と 言（い）って、部屋（へや）で 布（ぬの）を おりました。その 布（ぬの）は とても 高（たか）く 売（う）れました。ある 日（ひ）、男（おとこ）が こっそり のぞくと——そこには、自分（じぶん）の 羽根（はね）を ぬいて 布（ぬの）を おる 鶴（つる）の 姿（すがた）が ありました。正体（しょうたい）を 知（し）られた 妻（つま）は、空（そら）へ 飛（と）んで 行（い）きました。', "On a cold winter day, a man rescued a crane caught in a trap. That night, a beautiful woman visited his house and became his wife. She said, 'Please never look,' and wove cloth in a room. The cloth sold for a very high price. One day, when the man secretly peeked—there was the crane, plucking its own feathers to weave the cloth. Once her true form was known, the wife flew away into the sky.", '〜を 助ける／けっして〜ないで／〜と …が ある', '約束と恩返し。', '見てはいけない約束の結末。', '1話者・朗読'),
 ('昔話', '', '笠地蔵', '物語', 'N4', '年（とし）の くれ、まずしい おじいさんが、町（まち）へ 笠（かさ）を 売（う）りに 行（い）きました。でも、一（ひと）つも 売（う）れません。帰（かえ）り道（みち）、雪（ゆき）の 中（なか）に 立（た）つ 六（む）つの お地蔵（じぞう）さまを 見（み）つけました。『さむそうだ』と、おじいさんは 売（う）り物（もの）の 笠（かさ）を お地蔵（じぞう）さまに かぶせて あげました。一（ひと）つ 足（た）りないので、自分（じぶん）の 手（て）ぬぐいを かけました。その 夜（よる）、ふしぎな ことが おきました。朝（あさ）、戸（と）を 開（あ）けると、米（こめ）や もちが 山（やま）のように 置（お）いて あったのです。', "At year's end, a poor old man went to town to sell straw hats. But not one sold. On the way home, he found six Jizo statues standing in the snow. 'They look cold,' he said, and placed the hats he had been selling on the statues. One was short, so he used his own hand towel. That night, something mysterious happened. In the morning, when he opened the door, rice and mochi were piled up like a mountain.", '〜そうだ／〜て あげる／〜のように', '親切が返ってくる話。', '心温まる年越しの奇跡。', '1話者・朗読'),
]

def jc(s): return len(re.sub(r"[（(].*?[）)]|\s","",s))
wb=openpyxl.Workbook()
ws0=wb.active; ws0.title="説明"
for r in [
 ["短文コンテンツ（App B「聞いて話せる日本語」）",""],["",""],
 ["コンセプト","退屈な試験勉強に「楽しい!」を足し、娯楽感覚で継続学習。問題形式なし・精聴/精読がメイン。"],
 ["構成","タブ＝短文/長文。各3カテゴリー × サブテーマ × タイトル ＞ 音声+本文。短文/長文・カテゴリー間で内容を重複させない。"],
 ["短文(点・使える)","① 生活力 ② 使えるひとこと ③ ことば遊び（N5-N3）。自分が話す/手続き/覚える系。"],
 ["長文(らせん・娯楽)","① 日本語シャワー ② 物語 ③ 文化と本音（N4-N3+）。浴びる/読む/引き込まれる系。"],
 ["重複しない原則","行為で振り分け(話す/手続き=短文・浴びる/読む=長文)／素材は1か所だけ(コンビニ=短文,ニュース=長文,擬音語=短文,本音=長文)。"],
 ["対象レベル","各タイトルでバラバラ。★アプリ非表示（Excelのみ）。","",],
 ["形式","対話=多声TTS(役で声分け)／一人称・ニュース・天気・トーク・解説=1話者。"],
 ["出典","頭脳『生活場面スイートスポット』『コンテンツ設計_3AIアイデア統合』。"],
]: ws0.append(r)
ws0.column_dimensions["A"].width=16; ws0.column_dimensions["B"].width=95
ws0["A1"].font=Font(bold=True,size=13)
for row in ws0.iter_rows(min_row=3):
    row[0].font=Font(bold=True); row[1].alignment=Alignment(wrap_text=True,vertical="top")

HEAD=["ID","タブ","カテゴリー","サブテーマ","タイトル","形式","対象レベル(非表示)","本文","字数","英訳","キー表現","ポイント","楽しさ・継続フック","備考(音声)"]
WID={"A":7,"B":7,"C":13,"D":16,"E":20,"F":9,"G":14,"H":52,"I":6,"J":48,"K":30,"L":26,"M":26,"N":18}
def style(ws):
    f=PatternFill("solid",fgColor="1F4E79")
    for c in range(1,len(HEAD)+1):
        cell=ws.cell(row=1,column=c); cell.font=Font(bold=True,color="FFFFFF"); cell.fill=f
        cell.alignment=Alignment(horizontal="center",vertical="center",wrap_text=True)
    for col,w in WID.items(): ws.column_dimensions[col].width=w
    for row in ws.iter_rows(min_row=2):
        for cell in row: cell.alignment=Alignment(wrap_text=True,vertical="top")
    ws.freeze_panes="A2"

ws1=wb.create_sheet("短文"); ws1.append(HEAD)
for i,(cat,sub,ti,ke,lv,ho,en,key,po,fn,bk) in enumerate(TAN,1):
    ws1.append(["S-%03d"%i,"短文",cat,sub,ti,ke,lv,ho,jc(ho),en,key,po,fn,bk])
style(ws1)
ws2=wb.create_sheet("長文"); ws2.append(HEAD)
for i,(cat,sub,ti,ke,lv,ho,en,key,po,fn,bk) in enumerate(CHO,1):
    ws2.append(["L-%03d"%i,"長文",cat,sub,ti,ke,lv,ho,jc(ho),en,key,po,fn,bk])
style(ws2)
wb.save(OUT)
from collections import Counter
print("written",OUT)
print("短文:",len(TAN),"cat:",dict(Counter(x[0] for x in TAN)),"Lv:",dict(Counter(x[4] for x in TAN)))
print("長文:",len(CHO),"cat:",dict(Counter(x[0] for x in CHO)),"Lv:",dict(Counter(x[4] for x in CHO)))
